import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { CtaSection, IconCard, PageHero, SectionHeading } from "@/components/site";
import { systemDetails } from "@/components/data";

export const metadata: Metadata = { title: "Systems", description: "Smart property infrastructure systems including camera infrastructure, Wi-Fi foundation, access control systems, jobsite visibility, structured cabling, PoE, documentation, and operational handoff." };

export default function SystemsPage() {
  const principles = ["Infrastructure thinking, not gadget stacking", "PoE-first where practical", "Network and security planned together", "Documentation from day one", "Remote support readiness", "Operational handoff after installation"];
  return <><PageHero eyebrow="Systems" title="Smart property infrastructure, not random devices." copy="Sentinel designs property visibility systems around the infrastructure that makes them reliable: cameras, Wi-Fi, networking, access control, structured connectivity, documentation, and long-term support." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Systems built for visibility, uptime, and supportability." copy="Modern properties need more than equipment. They need an organized operating layer for visibility, access, networking, recording, and maintenance." /><div className="mt-10 grid gap-5 md:grid-cols-2">{systemDetails.map((system) => <IconCard key={system.title} {...system} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="The Sentinel architecture" title="Everything should connect, make sense, and be maintainable." copy="We recommend approved hardware stacks and serviceable ecosystems that support managed property systems, local video options, access control systems, Wi-Fi infrastructure, and operational visibility." /><div className="grid gap-3 sm:grid-cols-2">{principles.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section><CtaSection /></>;
}
