import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { CtaSection, IconCard, PageHero, SectionHeading } from "@/components/site";
import { serviceDetails } from "@/components/data";

export const metadata: Metadata = { title: "Services", description: "New camera system installation, Wi-Fi and network foundation, smart locks, access control, jobsite security systems, documentation, maintenance plans, and legacy system evaluation." };

export default function ServicesPage() {
  const standards = ["Preferred standardized systems", "Approved hardware stack", "Serviceable camera and network ecosystems", "Clean PoE-based security systems", "Locally stored video options", "Remote management-ready systems"];
  return <><PageHero eyebrow="Services" title="Clean property technology systems, built to be maintained." copy="Sentinel designs, installs, documents, and maintains camera, Wi-Fi, smart lock, access control, and jobsite security systems. We focus on systems we can stand behind, not random device chaos." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Install-first services for reliable security systems." copy="A security system is only valuable if it is designed correctly, installed cleanly, documented properly, and maintained over time." /><div className="mt-10 grid gap-5 md:grid-cols-2">{serviceDetails.map((service) => <IconCard key={service.title} {...service} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="Ecosystem thinking" title="We prefer serviceable systems over one-off device piles." copy="Sentinel recommends standardized hardware ecosystems that combine networking, Wi-Fi, cameras, access control, local video options, and remote management. We do not claim official partnership with any manufacturer unless specifically stated." /><div className="grid gap-3 sm:grid-cols-2">{standards.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section><CtaSection /></>;
}
