import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { CtaSection, IconCard, PageHero, SectionHeading } from "@/components/site";
import { systemDetails } from "@/components/data";

export const metadata: Metadata = { title: "Systems", description: "Premium smart property infrastructure including camera infrastructure, Wi-Fi connectivity, smart access, estate visibility, multi-property systems, continuity planning, documentation, and modular upgrades." };

export default function SystemsPage() {
  const principles = ["Premium infrastructure, not gadgets", "Clean PoE-first design where practical", "Topology visibility and documentation", "White-glove handoff", "Future upgrade architecture", "Remote support readiness", "Operational continuity planning", "Client portal compatibility"];
  return <><PageHero eyebrow="Systems" title="Premium infrastructure for serious property owners." copy="Sentinel designs property visibility systems around cameras, Wi-Fi, networking, access control, documentation, continuity, and modular upgrades. The goal is calm, documented, dependable technology that can evolve with the property." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Systems that create visible peace of mind." copy="Modern properties need an operating layer for visibility, access, connectivity, maintenance, upgrades, and long-term continuity." /><div className="mt-10 grid gap-5 md:grid-cols-2">{systemDetails.map((system) => <IconCard key={system.title} {...system} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="The Sentinel architecture" title="Everything should connect, make sense, and be maintainable." copy="We use UniFi-style ecosystem thinking as a model for modular infrastructure: integrated networking, Wi-Fi, cameras, access control, PoE switching, topology visibility, local storage options, remote management, and expandable systems. No official manufacturer partnership is claimed unless stated." /><div className="grid gap-3 sm:grid-cols-2">{principles.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section><CtaSection /></>;
}
