import type { Metadata } from "next";
import { CheckCircle2, XCircle } from "lucide-react";
import { CtaSection, PageHero, PlanCard, SectionHeading } from "@/components/site";
import { plans } from "@/components/data";

export const metadata: Metadata = { title: "Maintenance", description: "Premium maintenance memberships for smart property infrastructure, operational continuity, annual visibility reviews, storm readiness, travel readiness, reporting, and upgrade planning." };

export default function MaintenancePlansPage() {
  const fail = ["Cameras stop recording", "Wi-Fi weakens", "Passwords and app access drift", "Batteries die quietly", "Storage fills up", "Users and permissions become outdated"];
  const continuity = ["Annual visibility reviews", "Storm readiness", "Travel readiness", "Operational health reporting", "Upgrade planning", "Documentation updates", "Priority support for approved systems"];
  const mystery = ["Unsupported mystery DVR systems", "Rusted or unsafe equipment", "Unknown admin/password situations", "Disconnected apps and unmanaged accounts", "Poorly wired systems with no documentation", "Systems that need full replacement but are being patched endlessly"];
  return <><PageHero eyebrow="Maintenance" title="Protect the investment." copy="Installation creates the system. Maintenance protects the investment. Sentinel memberships preserve visibility, reliability, documentation, continuity, and long-term peace of mind." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading align="center" title="Maintenance is property continuity." copy="The best plans start with clean installation, documented access, serviceable equipment, and a realistic upgrade path." /><div className="mt-10 grid gap-5 lg:grid-cols-4">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-8 lg:grid-cols-2"><div><SectionHeading title="Why systems fail" copy="Most failures are quiet and operational. They do not announce themselves until an owner needs footage, access, or visibility." /><div className="mt-6 grid gap-3">{fail.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><XCircle className="mt-0.5 h-5 w-5 flex-none text-slate-500" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div><div><SectionHeading title="Why continuity matters" copy="Serious property owners need systems that are cared for, reviewed, improved, and ready when conditions change." /><div className="mt-6 grid gap-3">{continuity.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-green-600" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></div></section><section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading eyebrow="Sentinel Reserve" title="Invitation-style premium continuity." copy="Sentinel Reserve is for clients who want priority service, annual visibility reviews, travel readiness, storm readiness, upgrade planning, concierge support, and private client experience benefits." /><div className="rounded-md border border-slate-200 bg-frost p-6"><p className="leading-7 text-slate-700">Reserve is designed for high-end homes, estates, multi-property owners, and serious business properties where visibility and continuity matter beyond the initial installation.</p></div></div></section><section className="section-pad bg-ink text-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading light title="What creates mystery systems" copy="Some environments need a responsible replacement plan instead of endless patching." /><div className="grid gap-3 sm:grid-cols-2">{mystery.map((item) => <div key={item} className="rounded-md border border-white/10 bg-white/[0.04] p-4 text-sm font-semibold text-slate-200">{item}</div>)}</div></div></section><CtaSection /></>;
}
