import type { Metadata } from "next";
import { CheckCircle2, XCircle } from "lucide-react";
import { CtaSection, PageHero, PlanCard, SectionHeading } from "@/components/site";
import { plans } from "@/components/data";

export const metadata: Metadata = { title: "Maintenance Plans", description: "Security camera maintenance and property technology maintenance for Sentinel-installed, Sentinel-upgraded, and Sentinel-approved systems." };

export default function MaintenancePlansPage() {
  const maintain = ["Sentinel-installed systems", "Sentinel-upgraded systems", "Sentinel-approved systems after evaluation"];
  const notPrefer = ["Unsupported mystery DVR systems", "Rusted or unsafe equipment", "Unknown admin/password situations", "Poorly wired systems with no documentation", "Systems that need full replacement but are being patched endlessly"];
  return <><PageHero eyebrow="Maintenance Plans" title="Maintenance works best when the system is built to be serviced." copy="Recurring maintenance is the long-term core offer. Sentinel maintenance is designed for standardized, documented systems that we install, upgrade, or approve after evaluation." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading align="center" title="Maintenance is for systems worth maintaining." copy="The best plans start with a system that has clean installation, documented access, serviceable equipment, and a realistic upgrade path." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-8 lg:grid-cols-2"><div><SectionHeading title="What we maintain" copy="Sentinel maintenance is built around systems we can responsibly support over time." /><div className="mt-6 grid gap-3">{maintain.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-green-600" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div><div><SectionHeading title="What we do not prefer" copy="Some systems need a responsible replacement plan instead of endless patching." /><div className="mt-6 grid gap-3">{notPrefer.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><XCircle className="mt-0.5 h-5 w-5 flex-none text-slate-500" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></div></section><CtaSection /></>;
}
