import type { Metadata } from "next";
import { CheckCircle2, XCircle } from "lucide-react";
import { CtaSection, PageHero, PlanCard, SectionHeading } from "@/components/site";
import { plans } from "@/components/data";

export const metadata: Metadata = { title: "Maintenance", description: "Operational visibility maintenance for Sentinel-installed, Sentinel-upgraded, and Sentinel-approved smart property infrastructure systems." };

export default function MaintenancePlansPage() {
  const maintain = ["Sentinel-installed systems", "Sentinel-upgraded systems", "Sentinel-approved systems after evaluation", "Camera infrastructure", "Wi-Fi infrastructure", "Access control systems", "Smart property systems with clean documentation"];
  const mystery = ["Unsupported mystery DVR systems", "Rusted or unsafe equipment", "Unknown admin/password situations", "Disconnected apps and unmanaged accounts", "Poorly wired systems with no documentation", "Systems that need full replacement but are being patched endlessly"];
  const process = ["Review camera, network, access, and device health", "Confirm visibility, recording, and app access", "Document changes and maintenance notes", "Recommend updates, replacements, or optimization", "Provide priority support for approved systems"];
  const faq = [["Why standardization matters", "Standardized systems are easier to document, maintain, troubleshoot, and improve. Random devices create operational drag."], ["Why systems fail", "Most failures are quiet: weak Wi-Fi, storage issues, dead batteries, password changes, app disconnects, and neglected updates."], ["What maintenance creates", "Maintenance creates confidence that the systems protecting the property remain visible, connected, and operational."]];
  return <><PageHero eyebrow="Maintenance" title="Operational visibility requires ongoing maintenance." copy="Cameras, Wi-Fi, locks, access systems, recording, and apps all drift over time. Sentinel maintenance keeps smart property infrastructure operational, visible, updated, and supportable." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading align="center" title="Maintenance is the business model - not an afterthought." copy="The best plans start with clean installation, documented access, serviceable equipment, and a realistic upgrade path." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-8 lg:grid-cols-2"><div><SectionHeading title="What we maintain" copy="Sentinel maintenance is built around systems we can responsibly support over time." /><div className="mt-6 grid gap-3">{maintain.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-green-600" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div><div><SectionHeading title="What creates mystery systems" copy="Some environments need a responsible replacement plan instead of endless patching." /><div className="mt-6 grid gap-3">{mystery.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><XCircle className="mt-0.5 h-5 w-5 flex-none text-slate-500" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></div></section><section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading eyebrow="Maintenance process" title="How Sentinel keeps systems operational." copy="Recurring reviews turn quiet technology failure into managed infrastructure work." /><div className="grid gap-3">{process.map((item, index) => <div key={item} className="rounded-md border border-slate-200 bg-frost p-4"><p className="text-sm font-semibold text-ink">{index + 1}. {item}</p></div>)}</div></div></section><section className="section-pad bg-ink text-white"><div className="container-tight grid gap-5 md:grid-cols-3">{faq.map(([title, copy]) => <article key={title} className="rounded-md border border-white/10 bg-white/[0.04] p-6"><h2 className="font-display text-2xl font-semibold tracking-normal">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-300">{copy}</p></article>)}</div></section><CtaSection /></>;
}
