import type { Metadata } from "next";
import { resourceCategories } from "@/components/data";
import { CtaSection, PageHero, SectionHeading } from "@/components/site";

export const metadata: Metadata = { title: "Resources", description: "Sentinel Property Systems resource hub for property visibility, smart infrastructure, camera placement, Wi-Fi, upgrade planning, product recommendations, and maintenance education." };

export default function ResourcesPage() {
  const formats = ["Guides", "Tutorials", "Product recommendations", "Case studies", "Install breakdowns", "Upgrade ideas", "DIY education", "Maintenance education"];
  return <><PageHero eyebrow="Resources" title="Learn how modern property infrastructure actually works." copy="Sentinel publishes educational content, install breakdowns, upgrade ideas, blueprints, system-planning resources, and product recommendations for owners who want to make smarter property technology decisions." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Resource categories" copy="A content hub built for SEO, education, and better property technology decisions." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{resourceCategories.map((item) => <div key={item} className="rounded-md border border-slate-200 bg-frost p-5 text-sm font-semibold leading-6 text-ink">{item}</div>)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight"><SectionHeading title="Media and education formats" /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{formats.map((item) => <div key={item} className="rounded-md border border-slate-200 bg-white p-5 text-sm font-semibold text-ink shadow-sm">{item}</div>)}</div></div></section><section className="section-pad bg-ink text-white"><div className="container-tight"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-signal">Product recommendations</p><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Some links may generate affiliate commissions. Recommendations are intended to support clean, scalable, maintainable systems and do not imply official manufacturer partnership unless stated.</p></div></section><CtaSection /></>;
}
