import type { Metadata } from "next";
import { CheckCircle2, Radar } from "lucide-react";
import { CtaSection, PageHero } from "@/components/site";

export const metadata: Metadata = { title: "About", description: "Sentinel Property Systems creates operational clarity through clean smart property infrastructure installations, documentation, and ongoing maintenance." };

const values = ["Operational clarity over device chaos", "Clean installations that can be supported", "Documentation so systems do not become mysteries", "Maintenance plans that protect visibility over time"];

export default function AboutPage() {
  return <><PageHero eyebrow="About Sentinel" title="Built to bring order, visibility, and reliability to property technology." copy="Sentinel Property Systems was built around one realization: most property technology failures are not caused by missing equipment. They are caused by neglected systems." /><section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div className="rounded-md border border-slate-200 bg-frost p-6"><div className="grid h-14 w-14 place-items-center rounded-md bg-ink text-signal"><Radar className="h-8 w-8" /></div><p className="mt-6 text-lg font-semibold leading-8 text-ink">Sentinel is a property visibility and operational reliability company.</p></div><div><h2 className="font-display text-3xl font-semibold tracking-normal text-ink">Visibility disappears when systems are neglected.</h2><div className="mt-5 space-y-5 text-lg leading-8 text-slate-600"><p>Cameras fail quietly. Wi-Fi weakens over time. Locks stop being managed. Apps disconnect. Passwords disappear. Recording systems stop being checked.</p><p>Sentinel exists to create operational clarity through clean installations, system documentation, standardization, and ongoing maintenance. The goal is simple: you should never wonder whether your property systems are actually working.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{values.map((value) => <div key={value} className="flex gap-3 rounded-md border border-slate-200 p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{value}</p></div>)}</div></div></div></section><CtaSection /></>;
}
