import type { Metadata } from "next";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { CtaSection, PageHero } from "@/components/site";

export const metadata: Metadata = { title: "About", description: "Sentinel Property Systems is a local, practical, systems-minded property technology partner for smart security installation, documentation, and maintenance." };

const values = ["Install-first systems designed around serviceability", "Clean systems that owners can understand and manage", "Documentation so equipment does not become a mystery", "Maintenance plans for Sentinel-installed or approved systems"];

export default function AboutPage() {
  return <><PageHero eyebrow="About Sentinel" title="A local property technology partner built around one simple realization." copy="Most security problems are not caused by a lack of cameras. They are caused by neglected systems. Sentinel exists to install systems correctly and maintain them responsibly." /><section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div className="rounded-md border border-slate-200 bg-frost p-6"><div className="grid h-14 w-14 place-items-center rounded-md bg-ink text-signal"><ShieldCheck className="h-8 w-8" /></div><p className="mt-6 text-lg font-semibold leading-8 text-ink">Sentinel is local, practical, trustworthy, and systems-minded.</p></div><div><h2 className="font-display text-3xl font-semibold tracking-normal text-ink">Installed is not the same as protected.</h2><div className="mt-5 space-y-5 text-lg leading-8 text-slate-600"><p>Sentinel Property Systems was built around one simple realization: most security problems are not caused by a lack of cameras. They are caused by neglected systems. A camera that is offline, a lock no one manages, a Wi-Fi network that drops, or a recording system no one checks can create a false sense of security.</p><p>Sentinel exists to install smart security and property technology correctly, document it clearly, and maintain it over time. We install systems we can stand behind, then keep them working through recurring care for Sentinel-installed, upgraded, or approved systems.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{values.map((value) => <div key={value} className="flex gap-3 rounded-md border border-slate-200 p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{value}</p></div>)}</div></div></div></section><CtaSection /></>;
}
