import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { CtaSection, PageHero, SectionHeading } from "@/components/site";

export const metadata: Metadata = { title: "Sentinel Alpha", description: "Sentinel Alpha is the launch-stage proof-of-concept process for controlled systems, pilot client experiences, documentation standards, and white-glove delivery." };

export default function SentinelAlphaPage() {
  const cards = [["Internal demo/lab concept", "Sentinel HQ Alpha tests systems, content, standards, and workflows before broader launch."], ["First pilot client process", "A carefully selected premium pilot validates the full Sentinel journey."], ["Documentation standards", "Topology maps, device inventories, visibility plans, support records, and upgrade roadmaps."], ["White-glove delivery checklist", "Onboarding, communication, walkthrough, handoff, thank-you note, gift, and follow-up."]];
  const checklist = ["One real system", "One real client experience", "One real documentation standard", "One real maintenance workflow", "One real white-glove delivery model"];
  return <><PageHero eyebrow="Sentinel Alpha" title="Building the first undeniable system." copy="Sentinel Alpha is our launch-stage proof-of-concept process: one real system, one real client experience, one real documentation standard, one real maintenance workflow, and one real white-glove delivery model." cta="Apply for Pilot Consultation" /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Before scaling, Sentinel proves the operating system in reality." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{cards.map(([title, copy]) => <article key={title} className="rounded-md border border-slate-200 bg-frost p-6"><h2 className="font-display text-xl font-semibold tracking-normal text-ink">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading title="Alpha validation checklist" copy="The point is not volume. The point is proof, quality, documentation, and repeatability." /><div className="grid gap-3">{checklist.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section><CtaSection /></>;
}
