import { ArrowRight, Camera, CheckCircle2, KeyRound, Network, ShieldCheck, Wifi } from "lucide-react";
import { ButtonLink, CtaSection, IconCard, PlanCard, SectionHeading } from "@/components/site";
import { industries, plans, problems, services } from "@/components/data";

function SystemVisual() {
  const statusItems = [
    { label: "Cameras", value: "Online", icon: Camera },
    { label: "Access", value: "Synced", icon: KeyRound },
    { label: "Wi-Fi", value: "Strong", icon: Wifi },
    { label: "Network", value: "Stable", icon: Network }
  ];
  return <div className="relative overflow-hidden rounded-md border border-white/10 bg-[#07111f] p-4 shadow-glow"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(74,163,255,0.22),transparent_35%),linear-gradient(135deg,rgba(255,255,255,0.08),transparent_45%)]" /><div className="relative grid gap-4"><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Property Health</p><p className="mt-2 font-display text-2xl font-semibold text-white">Protected</p></div><div className="grid h-12 w-12 place-items-center rounded-md bg-signal text-ink"><ShieldCheck className="h-7 w-7" /></div></div><div className="mt-5 grid grid-cols-2 gap-3">{statusItems.map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-md border border-white/10 bg-ink/70 p-3"><Icon className="h-5 w-5 text-signal" /><p className="mt-3 text-xs text-slate-400">{item.label}</p><p className="text-sm font-semibold text-white">{item.value}</p></div>; })}</div></div><div className="grid gap-4 sm:grid-cols-[1.2fr_0.8fr]"><div className="min-h-64 rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Coverage Map</p><div className="relative mt-4 aspect-[4/3] rounded-md border border-signal/20 bg-[linear-gradient(rgba(74,163,255,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(74,163,255,0.08)_1px,transparent_1px)] bg-[size:26px_26px]"><div className="absolute left-[18%] top-[18%] h-16 w-24 rounded border border-signal/35 bg-signal/10" /><div className="absolute right-[16%] top-[22%] h-20 w-20 rounded border border-signal/35 bg-signal/10" /><div className="absolute bottom-[18%] left-[32%] h-20 w-32 rounded border border-signal/35 bg-signal/10" /><span className="absolute left-[28%] top-[35%] h-3 w-3 rounded-full bg-signal shadow-[0_0_24px_rgba(74,163,255,0.9)]" /><span className="absolute bottom-[28%] right-[22%] h-3 w-3 rounded-full bg-green-400 shadow-[0_0_24px_rgba(74,222,128,0.8)]" /></div></div><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Checkup Log</p><ul className="mt-4 grid gap-3">{["Camera angles verified", "Firmware reviewed", "App access confirmed", "Recording checked"].map((item) => <li key={item} className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-5 w-5 flex-none text-green-400" />{item}</li>)}</ul></div></div></div></div>;
}

export default function HomePage() {
  const differentiators = ["We check what others forget.", "We clean up messy systems.", "We help owners understand their apps and access.", "We maintain the devices that protect your property.", "We design systems with serviceability in mind.", "We focus on uptime, visibility, and peace of mind."];
  const steps = [["Property Tech Checkup", "We inspect your current cameras, Wi-Fi, smart locks, access control, recording, apps, and weak points."], ["Clear Recommendations", "You get a simple action plan: fix, maintain, upgrade, or replace."], ["Install or Repair", "We handle clean installs, system rescue, device setup, network support, and troubleshooting."], ["Ongoing Maintenance", "Choose a plan so your system does not quietly fail again."]];
  return <>
    <section className="section-pad overflow-hidden bg-ink text-white"><div className="container-tight grid items-center gap-12 pt-10 lg:grid-cols-[0.95fr_1.05fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.24em] text-signal">Smart Security & Property Technology Maintenance</p><h1 className="mt-6 font-display text-4xl font-semibold tracking-normal sm:text-6xl lg:text-7xl">Security systems are only useful when they actually work.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Sentinel Property Systems helps homeowners and businesses install, maintain, troubleshoot, and monitor cameras, smart locks, access control, Wi-Fi, and connected property technology.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" variant="primary">Schedule a Property Tech Checkup <ArrowRight className="h-4 w-4" /></ButtonLink><ButtonLink href="/services" variant="secondary">View Services</ButtonLink></div><p className="mt-6 text-sm font-medium text-slate-300">Serving homes, small businesses, contractors, and commercial properties.</p></div><SystemVisual /></div></section>
    <section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Most security systems fail quietly." copy="Cameras go offline. Batteries die. Wi-Fi drops. Notifications stop working. NVRs fill up. Passwords get lost. Apps disconnect. By the time someone notices, the system may have been useless for weeks." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problems.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading eyebrow="The Sentinel approach" title="We keep your property technology alive." copy="Sentinel installs, maintains, and supports smart security systems so your property stays protected and your technology keeps doing its job." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-tight"><SectionHeading align="center" title="Protection should not end after installation." copy="Security camera maintenance, updates, access checks, and support should be part of the system from day one." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight"><SectionHeading light title="Built for properties that cannot afford blind spots." copy="Homes, storefronts, offices, worship spaces, rentals, warehouses, and jobsites all need systems that stay online after the installer leaves." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{industries.map((industry) => <IconCard key={industry.title} {...industry} dark />)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="Why Sentinel" title="Not just installs. Ongoing property technology support." copy="Sentinel is built for the long tail of ownership: the updates, batteries, passwords, blind spots, and connectivity issues that decide whether a system is actually useful." /><div className="grid gap-3 sm:grid-cols-2">{differentiators.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-frost p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading title="How it works" /><div className="mt-10 grid gap-5 lg:grid-cols-4">{steps.map(([title, copy], index) => <article key={title} className="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-md bg-ink text-sm font-semibold text-white">{index + 1}</span><h3 className="mt-5 font-display text-xl font-semibold tracking-normal text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
    <CtaSection />
  </>;
}
