import { ArrowRight, Camera, CheckCircle2, FileText, KeyRound, Network, ShieldCheck, Wifi } from "lucide-react";
import { ButtonLink, CtaSection, IconCard, PlanCard, SectionHeading } from "@/components/site";
import { industries, plans, problems, services } from "@/components/data";

function SystemVisual() {
  const statusItems = [{ label: "Cameras", value: "Planned", icon: Camera }, { label: "Access", value: "Documented", icon: KeyRound }, { label: "Wi-Fi", value: "Serviceable", icon: Wifi }, { label: "Network", value: "Managed", icon: Network }];
  return <div className="relative overflow-hidden rounded-md border border-white/10 bg-[#07111f] p-4 shadow-glow"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(74,163,255,0.22),transparent_35%),linear-gradient(135deg,rgba(255,255,255,0.08),transparent_45%)]" /><div className="relative grid gap-4"><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Sentinel System</p><p className="mt-2 font-display text-2xl font-semibold text-white">Install + Maintain</p></div><div className="grid h-12 w-12 place-items-center rounded-md bg-signal text-ink"><ShieldCheck className="h-7 w-7" /></div></div><div className="mt-5 grid grid-cols-2 gap-3">{statusItems.map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-md border border-white/10 bg-ink/70 p-3"><Icon className="h-5 w-5 text-signal" /><p className="mt-3 text-xs text-slate-400">{item.label}</p><p className="text-sm font-semibold text-white">{item.value}</p></div>; })}</div></div><div className="grid gap-4 sm:grid-cols-[1.2fr_0.8fr]"><div className="min-h-64 rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Coverage Map</p><div className="relative mt-4 aspect-[4/3] rounded-md border border-signal/20 bg-[linear-gradient(rgba(74,163,255,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(74,163,255,0.08)_1px,transparent_1px)] bg-[size:26px_26px]"><div className="absolute left-[18%] top-[18%] h-16 w-24 rounded border border-signal/35 bg-signal/10" /><div className="absolute right-[16%] top-[22%] h-20 w-20 rounded border border-signal/35 bg-signal/10" /><div className="absolute bottom-[18%] left-[32%] h-20 w-32 rounded border border-signal/35 bg-signal/10" /><span className="absolute left-[28%] top-[35%] h-3 w-3 rounded-full bg-signal shadow-[0_0_24px_rgba(74,163,255,0.9)]" /><span className="absolute bottom-[28%] right-[22%] h-3 w-3 rounded-full bg-green-400 shadow-[0_0_24px_rgba(74,222,128,0.8)]" /></div></div><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">System File</p><ul className="mt-4 grid gap-3">{["Device list", "Network layout", "Access notes", "Maintenance plan"].map((item) => <li key={item} className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-5 w-5 flex-none text-green-400" />{item}</li>)}</ul></div></div></div></div>;
}

export default function HomePage() {
  const noMystery = ["Clear device list", "Clean network layout", "Labeled equipment where practical", "Documented app/admin access", "Camera placement notes", "Maintenance recommendations", "Upgrade path when needed"];
  const legacyOptions = ["Stabilize what is working", "Replace failed components", "Upgrade to a supported system", "Start fresh with a Sentinel-standard installation"];
  const steps = [["Consultation", "We learn the property, the risks, the devices needed, and what has failed before."], ["System Design", "We recommend a clean, standardized system that can be installed and maintained."], ["Professional Installation", "We install cameras, networking, Wi-Fi, locks, access control, and related property technology."], ["Documentation", "We document the system so it does not become a mystery later."], ["Maintenance Plan", "We keep the system healthy through scheduled checkups and priority support."]];
  return <>
    <section className="section-pad overflow-hidden bg-ink text-white"><div className="container-tight grid items-center gap-12 pt-10 lg:grid-cols-[0.95fr_1.05fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.24em] text-signal">Smart Security Systems. Professionally Installed. Reliably Maintained.</p><h1 className="mt-6 font-display text-4xl font-semibold tracking-normal sm:text-6xl lg:text-7xl">Security systems should not be a mystery after install day.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Sentinel Property Systems installs clean, reliable camera, Wi-Fi, smart lock, and access control systems, then maintains them so they keep working when you need them.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" variant="primary">Schedule a Property Tech Consultation <ArrowRight className="h-4 w-4" /></ButtonLink><ButtonLink href="/maintenance-plans" variant="secondary">View Maintenance Plans</ButtonLink></div><p className="mt-6 text-sm font-medium text-slate-300">Install-first. Maintenance-focused. Built for homes, businesses, and jobsite properties.</p></div><SystemVisual /></div></section>
    <section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Most security systems fail because nobody owns the system after installation." copy="Cameras go offline. Apps stop working. Wi-Fi drops. Passwords get lost. Recording systems fill up. Batteries die. Wires are unlabeled. No one knows who installed what, how it connects, or whether it still works." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problems.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading eyebrow="The Sentinel approach" title="We install systems we can maintain." copy="Sentinel focuses on clean, serviceable installations using standardized equipment, documented layouts, and maintenance-ready designs. Instead of leaving you with a pile of disconnected devices, we build a system that can be supported over time." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading light eyebrow="Our rule" title="No mystery systems." copy="Every Sentinel installation is designed to be understood, supported, and maintained. We recommend preferred standardized systems and approved hardware stacks that make long-term service realistic." /><div className="grid gap-3 sm:grid-cols-2">{noMystery.map((item) => <div key={item} className="flex gap-3 rounded-md border border-white/10 bg-white/[0.04] p-4"><FileText className="mt-0.5 h-5 w-5 flex-none text-signal" /><p className="text-sm font-medium leading-6 text-slate-200">{item}</p></div>)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-tight"><SectionHeading align="center" title="Maintenance is for systems worth maintaining." copy="The best maintenance plans start with systems installed correctly. Sentinel maintenance is designed for systems we install, upgrade, document, or approve after evaluation." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="Legacy systems" title="Have an old system? We start with an evaluation, not an open-ended repair promise." copy="Some systems are worth saving. Some are not. If your current cameras, DVR, wiring, locks, or Wi-Fi setup are undocumented, outdated, rusted, unsupported, or unreliable, we will inspect the system and give you a clear recommendation." /><div className="grid gap-3">{legacyOptions.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}<p className="rounded-md border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600">We do not offer unlimited troubleshooting for unsupported legacy systems. Our goal is to help you make the smartest decision: maintain, upgrade, or replace.</p></div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight"><SectionHeading light title="Built for properties that need dependable visibility." copy="Homes, storefronts, offices, worship spaces, rentals, warehouses, and jobsites all need systems that stay online after the installer leaves." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{industries.map((industry) => <IconCard key={industry.title} {...industry} dark />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading title="How Sentinel works" /><div className="mt-10 grid gap-5 lg:grid-cols-5">{steps.map(([title, copy], index) => <article key={title} className="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-md bg-ink text-sm font-semibold text-white">{index + 1}</span><h3 className="mt-5 font-display text-xl font-semibold tracking-normal text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="section-pad bg-steel text-white"><div className="container-tight"><div className="grid items-center gap-8 rounded-md border border-white/10 bg-ink p-8 shadow-glow lg:grid-cols-[1fr_auto] lg:p-10"><div><h2 className="font-display text-3xl font-semibold tracking-normal">Stop buying security systems that nobody maintains.</h2><p className="mt-3 max-w-3xl text-lg leading-8 text-slate-300">Get a clean, serviceable Sentinel system installed and maintained from day one.</p></div><ButtonLink href="/contact" variant="primary">Schedule a Consultation <ArrowRight className="h-4 w-4" /></ButtonLink></div></div></section>
  </>;
}
