import { ArrowRight, Camera, CheckCircle2, FileText, KeyRound, Network, Radar, ShieldCheck, Wifi } from "lucide-react";
import { ButtonLink, CtaSection, IconCard, PlanCard, SectionHeading } from "@/components/site";
import { industries, plans, problems, systems } from "@/components/data";

function SystemVisual() {
  const nodes = [{ label: "Cameras", value: "Online", icon: Camera }, { label: "Access", value: "Managed", icon: KeyRound }, { label: "Wi-Fi", value: "Healthy", icon: Wifi }, { label: "Network", value: "Mapped", icon: Network }];
  return <div className="relative overflow-hidden rounded-md border border-white/10 bg-[#07111f] p-4 shadow-glow"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(74,163,255,0.22),transparent_35%),linear-gradient(135deg,rgba(255,255,255,0.08),transparent_45%)]" /><div className="relative grid gap-4"><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Managed Smart Property Infrastructure</p><p className="mt-2 font-display text-2xl font-semibold text-white">Visibility + Reliability</p></div><div className="grid h-12 w-12 place-items-center rounded-md bg-signal text-ink"><Radar className="h-7 w-7" /></div></div><div className="mt-5 grid grid-cols-2 gap-3">{nodes.map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-md border border-white/10 bg-ink/70 p-3"><Icon className="h-5 w-5 text-signal" /><p className="mt-3 text-xs text-slate-400">{item.label}</p><p className="text-sm font-semibold text-white">{item.value}</p></div>; })}</div></div><div className="grid gap-4 sm:grid-cols-[1.2fr_0.8fr]"><div className="min-h-64 rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Signal Map</p><div className="relative mt-4 aspect-[4/3] rounded-md border border-signal/20 bg-[linear-gradient(rgba(74,163,255,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(74,163,255,0.08)_1px,transparent_1px)] bg-[size:26px_26px]"><div className="absolute left-[12%] top-[18%] h-16 w-28 rounded border border-signal/35 bg-signal/10" /><div className="absolute right-[13%] top-[20%] h-20 w-20 rounded border border-signal/35 bg-signal/10" /><div className="absolute bottom-[18%] left-[32%] h-20 w-32 rounded border border-signal/35 bg-signal/10" /><span className="absolute left-[26%] top-[36%] h-3 w-3 rounded-full bg-signal shadow-[0_0_24px_rgba(74,163,255,0.9)]" /><span className="absolute bottom-[27%] right-[20%] h-3 w-3 rounded-full bg-green-400 shadow-[0_0_24px_rgba(74,222,128,0.8)]" /><span className="absolute left-[38%] top-[58%] h-px w-[34%] rotate-[-18deg] bg-signal/60 shadow-[0_0_16px_rgba(74,163,255,0.8)]" /></div></div><div className="rounded-md border border-white/10 bg-white/[0.04] p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">System Health</p><ul className="mt-4 grid gap-3">{["Documented", "Connected", "Maintained", "Visible"].map((item) => <li key={item} className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-5 w-5 flex-none text-green-400" />{item}</li>)}</ul></div></div></div></div>;
}

export default function HomePage() {
  const trust = ["Clean Installations", "Documented Systems", "Maintenance-Focused", "Network + Security", "Property Visibility"];
  const standard = ["Approved hardware stack", "Clean PoE-first design", "Maintenance-ready infrastructure", "Organized network layout", "Documented device inventory", "Camera placement documentation", "Admin/app handoff", "Upgrade path planning", "Remote support readiness", "Operational visibility planning"];
  const legacyOptions = ["Stabilize existing infrastructure", "Replace failed components", "Upgrade critical systems", "Full Sentinel-standard rebuild"];
  const steps = [["Consultation", "Understand the property, risks, goals, visibility requirements, and existing issues."], ["System Design", "Create a clean, maintainable, visibility-focused infrastructure plan."], ["Professional Installation", "Install networking, Wi-Fi, cameras, access systems, and smart infrastructure."], ["Documentation", "Map and document the environment so it never becomes a mystery."], ["Maintenance", "Keep systems operational through recurring support and visibility reviews."]];
  return <>
    <section className="section-pad overflow-hidden bg-ink text-white"><div className="container-tight grid items-center gap-12 pt-10 lg:grid-cols-[0.95fr_1.05fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.24em] text-signal">Operational Visibility for Modern Properties</p><h1 className="mt-6 font-display text-4xl font-semibold tracking-normal sm:text-6xl lg:text-7xl">Operational Visibility for Modern Properties</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Sentinel Property Systems installs, documents, standardizes, and maintains smart property infrastructure - including cameras, Wi-Fi, networking, access control, and smart security systems - so your property stays visible, connected, and operational.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" variant="primary">Schedule a Property Systems Consultation <ArrowRight className="h-4 w-4" /></ButtonLink><ButtonLink href="/maintenance-plans" variant="secondary">Explore Maintenance Plans</ButtonLink></div><div className="mt-7 flex flex-wrap gap-2">{trust.map((item) => <span key={item} className="rounded-md border border-white/10 bg-white/[0.06] px-3 py-2 text-xs font-semibold text-slate-200">{item}</span>)}</div><p className="mt-6 text-sm font-medium text-slate-300">You should never wonder whether your systems are actually working.</p></div><SystemVisual /></div></section>
    <section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Most property systems quietly fail over time." copy="Cameras go offline. Wi-Fi weakens. Apps disconnect. Passwords disappear. Recording systems stop recording. Wiring becomes undocumented. Nobody owns the system after installation. Many properties operate with a false sense of security because nobody maintains the infrastructure that supports visibility and access." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problems.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight grid gap-8 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading light eyebrow="The Reframe" title="Security is not equipment. It is operational reliability." copy="A camera that is offline is not security. A smart lock nobody manages is not access control. A recording system nobody checks is not protection." /><div className="rounded-md border border-white/10 bg-white/[0.04] p-6 text-lg leading-8 text-slate-300">Operational visibility only exists when systems are designed correctly, documented clearly, and maintained consistently. Sentinel builds systems that stay operational.</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading eyebrow="The Solution" title="We install systems we can stand behind." copy="Sentinel creates standardized smart property environments designed for long-term support, visibility, and maintainability." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{systems.map((card) => <IconCard key={card.title} {...card} />)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading eyebrow="The Sentinel Standard" title="No mystery systems." copy="Every Sentinel installation is designed to remain understandable, maintainable, and supportable long after install day." /><div className="grid gap-3 sm:grid-cols-2">{standard.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-frost p-4"><FileText className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight"><SectionHeading light align="center" title="Maintenance is the business model - not an afterthought." copy="Most property systems fail because nobody owns the infrastructure after installation. Sentinel maintenance plans keep systems operational, visible, updated, and supportable over time." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <PlanCard key={plan.name} {...plan} />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionHeading eyebrow="Legacy Systems" title="Have an old system? Start with clarity." copy="Some systems are worth stabilizing. Some are worth upgrading. Some should be replaced entirely. Sentinel evaluates legacy systems and recommends the smartest operational path forward." /><div className="grid gap-3">{legacyOptions.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}<p className="rounded-md border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600">We do not offer unlimited troubleshooting for unsupported mystery systems. Our goal is to help clients make intelligent operational decisions.</p><ButtonLink href="/legacy-evaluation" variant="dark">Request Legacy Evaluation <ArrowRight className="h-4 w-4" /></ButtonLink></div></div></section>
    <section className="section-pad bg-ink text-white"><div className="container-tight"><SectionHeading light title="Built for properties that require dependable visibility." copy="Homes, storefronts, offices, worship spaces, rentals, warehouses, jobsites, and multi-property operations all need systems that stay operational after install day." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry) => <IconCard key={industry.title} {...industry} dark />)}</div></div></section>
    <section className="section-pad bg-frost"><div className="container-tight"><SectionHeading title="How Sentinel works" /><div className="mt-10 grid gap-5 lg:grid-cols-5">{steps.map(([title, copy], index) => <article key={title} className="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-md bg-ink text-sm font-semibold text-white">{index + 1}</span><h3 className="mt-5 font-display text-xl font-semibold tracking-normal text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
    <CtaSection />
  </>;
}
