import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { blueprintOffers } from "@/components/data";
import { CtaSection, PageHero, SectionHeading } from "@/components/site";

export const metadata: Metadata = { title: "Blueprints", description: "Professional smart property infrastructure blueprints, checklists, planning guides, DIY support, shopping lists, and consultation pathways." };

export default function BlueprintsPage() {
  const details = ["Free checklist for initial clarity", "Starter blueprint for focused properties", "Executive blueprint for serious homes", "Estate blueprint for larger environments", "Custom blueprint for unique properties", "DIY support and shopping lists", "Consultation upsells for owners ready to build"];
  return <><PageHero eyebrow="Blueprints" title="Professional infrastructure planning for serious property owners." copy="Start with clarity before you buy devices, hire installers, or add more apps. Sentinel blueprints help owners understand visibility, connectivity, access, maintenance, and upgrade paths before committing to a full project." /><section className="section-pad bg-white"><div className="container-tight"><SectionHeading title="Blueprint offers" copy="Planning tools for owners who want smart property systems without chaos." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{blueprintOffers.map((item) => <div key={item} className="rounded-md border border-slate-200 bg-frost p-5 text-sm font-semibold leading-6 text-ink">{item}</div>)}</div></div></section><section className="section-pad bg-frost"><div className="container-tight grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading title="DIY education that can lead into professional execution." copy="Sentinel can educate DIYers and planners while still protecting the premium installation brand. Blueprints help owners make better decisions and create cleaner projects." /><div className="grid gap-3 sm:grid-cols-2">{details.map((item) => <div key={item} className="flex gap-3 rounded-md border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-steel" /><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></div>)}</div></div></section><section className="section-pad bg-ink text-white"><div className="container-tight"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-signal">Affiliate disclosure</p><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Some product links may generate affiliate commissions. Sentinel only recommends products that align with the Sentinel Standard: serviceable, scalable, reliable, and maintainable.</p></div></section><CtaSection /></>;
}
